/**
* kokoro.io API document
* X-Access-Token ヘッダーにあなたのアカウントのAPIトークンを含めることでAPIへのアクセスを行うことが出来ます。APIトークンはウェブ管理画面の右上メニュー「アカウント情報 > API情報」から確認可能です。  ただし、 POST /api/v1/devices/ APIへのリクエスト時のみ、APIトークンではなくあなたのアカウント情報を用いて認証を行うことが出来ます。この場合、X-Access-TokenではなくX-Account-Token ヘッダーを使用し、その値にはアカウントのメールアドレスとパスワードをコロンで連結した文字列 \"[email]:[password]\" を Base64 エンコードしたものを指定してください。  また、このページ右上の「Your API token here」の欄にAPIトークンを入力し「Explore」ボタンをクリックすることで、このページの各API説明部分にある「Try it out!」ボタンから実際にAPIを呼び出すことが可能になります。この時、通常のAPI呼び出しと同様、アカウントへの操作が実際に行われますのでご注意ください。 
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.AvatarEntity

/**
 * Returns all user's profile except yours
 * @param id プロフィールID
 * @param type 種類（user|bot）
 * @param screen_name スクリーンネーム
 * @param display_name ディスプレイネーム
 * @param avatar アバターURL
 * @param avatars 
 * @param archived アーカイブ済か
 * @param invited_channels_count 招待されているチャンネルの数
 */
data class ProfileEntity (
    /* プロフィールID */
    val id: kotlin.String? = null,
    /* 種類（user|bot） */
    val type: kotlin.String? = null,
    /* スクリーンネーム */
    val screen_name: kotlin.String? = null,
    /* ディスプレイネーム */
    val display_name: kotlin.String? = null,
    /* アバターURL */
    val avatar: kotlin.String? = null,
    /*  */
    val avatars: kotlin.Array<AvatarEntity>? = null,
    /* アーカイブ済か */
    val archived: kotlin.Boolean? = null,
    /* 招待されているチャンネルの数 */
    val invited_channels_count: kotlin.Int? = null
) {

}

