/**
* kokoro.io API document
* X-Access-Token ヘッダーにあなたのアカウントのAPIトークンを含めることでAPIへのアクセスを行うことが出来ます。APIトークンはウェブ管理画面の右上メニュー「アカウント情報 > API情報」から確認可能です。  ただし、 POST /api/v1/devices/ APIへのリクエスト時のみ、APIトークンではなくあなたのアカウント情報を用いて認証を行うことが出来ます。この場合、X-Access-TokenではなくX-Account-Token ヘッダーを使用し、その値にはアカウントのメールアドレスとパスワードをコロンで連結した文字列 \"[email]:[password]\" を Base64 エンコードしたものを指定してください。  また、このページ右上の「Your API token here」の欄にAPIトークンを入力し「Explore」ボタンをクリックすることで、このページの各API説明部分にある「Try it out!」ボタンから実際にAPIを呼び出すことが可能になります。この時、通常のAPI呼び出しと同様、アカウントへの操作が実際に行われますのでご注意ください。 
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.github.raa0121.kokoroio.model


/**
 * Delete a access_token
 * @param id アクセストークンID
 * @param name アクセストークン名
 * @param token アクセストークン
 * @param kind アクセストークン種別
 */
data class AccessTokenEntity (
    /* アクセストークンID */
    val id: kotlin.String? = null,
    /* アクセストークン名 */
    val name: kotlin.String? = null,
    /* アクセストークン */
    val token: kotlin.String? = null,
    /* アクセストークン種別 */
    val kind: AccessTokenEntity.Kind? = null
) {

    /**
    * アクセストークン種別
    * Values: user,device,essential
    */
    enum class Kind(val value: kotlin.Any){
    
        user("user"),
    
        device("device"),
    
        essential("essential");
    
    }

}

